config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  get 'storefront/index'

  resources :products
  resources :brands
  resources :categories
  #root 'visitors#index'
  devise_for :users

  root 'storefront#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy
  validates :name, :address, :user_id, presence: true

  PAYMENT_TYPES = ["Check", "Credit Card", "PayPal"]
  validates :payment_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  
  def subtotal
    line_items.to_a.sum { |item| item.total_price}
  end
end





# == Schema Information
#
# Table name: orders
#
#  id           :integer          not null, primary key
#  name         :string
#  address      :text
#  payment_type :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_orders_on_user_id  (user_id)
#

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart   #this grabs to module
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to storefront_index_url, notice: "Your cart is empty."
      return
    end

    @order = Order.new
    @order.user_id = current_user.id
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        #Deliver order confirmation email
        OrderConfirmation.send_order_confirmation(current_user, @order).deliver_now

        #Reset the session cart to be empty
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil

        format.html { redirect_to storefront_index_url, notice: 'Thank you for your order!.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :payment_type, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Jane-Smith" %>
  </div>
  <div class="field form-group">
    <%= f.label :address, placeholder: "100 St. Charles Ave\nNew Orleans, LA 70115" %><br>
    <%= f.text_area :address, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :payment_type %><br>
    <%= f.select :payment_type, Order::PAYMENT_TYPES, {prompt: "Select a payment method"}, {class: "form-control"} %>
  </div>
 
  <div class="actions">
    <%= f.submit "Place Order", class: "btn btn-success" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Payment Type</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td> 
        <td><%= order.payment_type %></td>
        <td><%= order.user.try(:email) %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back to Cart', cart_path(session[:cart_id]) %>

app/views/orders/show.html.erb
<p>
  <strong>Ship To Name:</strong>
  <%= @order.try(:name) %>
</p>

<p>
  <strong>Ship To Address:</strong>
  <%= @order.try(:address) %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @order.try(:payment_type) %>
</p>

<p>
  <strong>User Email:</strong>
  <%= @order.try(:user).try(:email) %>
</p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %> &times;</td>
        <td><%= number_to_currency item.price %></td>
        <td><%= number_to_currency item.total_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Order Subtotal: <%= number_to_currency @order.subtotal %></h3>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>